# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"
  base = "apps/web-app"
  [build.environment]
    NETLIFY_EXPERIMENTAL_BUILD_NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  targetPort = 5173
  framework = "#custom"

[functions]
  directory = "../../netlify/functions"
  included_files = ["../../netlify/functions/**"]
  [functions."*"]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]


[[redirects]]
  from = "/api/jira/config"
  to = "/.netlify/functions/jira-config"
  status = 200

[[redirects]]
  from = "/api/jira/projects"
  to = "/.netlify/functions/jira-proxy"
  status = 200

[[redirects]]
  from = "/api/jira/sprints"
  to = "/.netlify/functions/jira-proxy"
  status = 200

[[redirects]]
  from = "/api/jira/issues"
  to = "/.netlify/functions/jira-proxy"
  status = 200

[[redirects]]
  from = "/api/jira-proxy"
  to = "/.netlify/functions/jira-proxy"
  status = 200

[[redirects]]
  from = "/api/kpi"
  to = "/.netlify/functions/api-kpi"
  status = 200

# Trigger new deploy to clear cache
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
