# netlify.toml
[build]
  # Comando para construir el proyecto. Se ejecuta desde la raíz.
  command = "npm run build"
  # Directorio donde se publica el resultado del build.
  publish = "dist/"
  # Directorio donde Netlify buscará las Edge Functions.
  edge_functions = "netlify/edge-functions"

# Declaración explícita de la Edge Function y su ruta.
# Esto reemplaza la necesidad de una redirección.
[[edge_functions]]
  path = "/api/*"
  function = "jira-proxy"
