# netlify.toml

[build]
  # Comando para construir el proyecto. Se ejecuta desde la raíz.
  command = "vite build"
  # Directorio donde se publica el resultado del build.
  publish = "dist"
  # Directorio donde se encuentran las edge functions.
  edge_functions = "netlify/edge-functions"


[dev]
  command = "vite"
  functions = "netlify/functions"

[functions]
  [functions."*"]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[edge_functions]]
path = "/api/*"
function = "jira-proxy"
excludedPattern = "^/netlify/blobs/|^/api/kpi"



[[redirects]]
  from = "/api/kpi"
  to = "/.netlify/functions/api-kpi"
  status = 200

# Trigger new deploy to clear cache
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
